language: cpp
compiler:
  - gcc
python:
  - "2.6"
script: make --directory=test
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-all-dev
notifications:
  recipients:
    - yuanyang_wu@hotmail.com
  email:
    on_success: change
    on_failure: always
