
# to be replaced with json file path
JSON_FILE := ../../TO_REPLACE_JSON_FILE

OUTPUT_APP := output/bin/test

CLIENT_SRC_FILES := $(wildcard $(CURDIR)/src/*.cpp)
CLIENT_OBJ_FILES := $(patsubst $(CURDIR)/src/%.cpp, $(CURDIR)/output/obj/%.o, $(CLIENT_SRC_FILES))

JSONSPIRIT_DIR=$(CURDIR)/../../../depends/json_spirit/output/dist

CFLAGS := \
	-I$(CURDIR)/src \
	-I$(JSONSPIRIT_DIR)/include \
	-g -O \

STRICT_CFLAGS := $(CFLAGS) -Wall

LDFLAGS := -g -O -Wall \


default: init $(OUTPUT_APP)

init:
	@mkdir -p output/bin
	@mkdir -p output/obj

clean:
	rm -fr output

run: $(OUTPUT_APP)
	@$(OUTPUT_APP) ${JSON_FILE} | tee output/bin/out.json
	@../../../util/diff_json.py $(JSON_FILE) output/bin/out.json

$(OUTPUT_APP): $(CLIENT_OBJ_FILES)
	g++ -o $@ $^ $(LDFLAGS) $(JSONSPIRIT_DIR)/lib/libjson_spirit.a

$(CURDIR)/output/obj/%.o: $(CURDIR)/src/%.cpp
	g++ $(STRICT_CFLAGS) -c $< -o $@

