
OUTPUT_LIB := output/bin/libjson_spirit.a

CLIENT_SRC_FILES := $(wildcard $(CURDIR)/src/*.cpp)
CLIENT_OBJ_FILES := $(patsubst $(CURDIR)/src/%.cpp, $(CURDIR)/output/obj/%.o, $(CLIENT_SRC_FILES))

CFLAGS := \
	-I$(CURDIR)/src \
	-g -O \

STRICT_CFLAGS := $(CFLAGS) -Wall

LDFLAGS := -g -O -Wall \


default: init $(OUTPUT_LIB)

init:
	@mkdir -p output/bin
	@mkdir -p output/obj

clean:
	rm -fr output

run: $(OUTPUT_APP)
	@$(OUTPUT_APP)

$(OUTPUT_LIB): $(CLIENT_OBJ_FILES)
	rm -f $@
	ar -cvq $@ $^

$(CURDIR)/output/obj/%.o: $(CURDIR)/src/%.cpp
	g++ $(STRICT_CFLAGS) -c $< -o $@

